version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USER: "/dockerhub/credentials:username"
    DOCKERHUB_PASS: "/dockerhub/credentials:password"

phases:
  pre_build:
    commands:
      - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASS
      - apt-get update
      - apt-get install -y qemu-system-arm qemu-user-static unzip curl apt-transport-https ca-certificates python-pip
  build:
    commands:
      - docker build -t connollyst/rpi-aws-iot-etape:latest .
  post_build:
    commands:
      - docker push connollyst/rpi-aws-iot-etape:latest
artifacts:
  files:
    - '**/*'
  base-directory: src/main/python