version: 0.2

#env:
#  secrets-manager:
#    DOCKERHUB_USER: "/dockerhub/credentials:username"
#    DOCKERHUB_PASS: "/dockerhub/credentials:password"

phases:
  install:
    commands:
      - apt update
      - apt install curl
      - curl -sSL https://get.docker.com | sh
  #      - apt-get update
  #      - apt-get install -y qemu-system-arm qemu-user-static
  #  pre_build:
  #    commands:
  #      - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASS
  #- pip install -r requirements.txt
  build:
    commands:
      #- python -m unittest discover -s src/test/python/app
      - docker build -t connollyst/rpi-aws-iot-etape:latest .
#  post_build:
#    commands:
#      - docker push connollyst/rpi-aws-iot-etape:latest
artifacts:
  files:
    - '**/*'
  base-directory: src/main/python